# Generated by Django 5.1.3 on 2024-11-19 11:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='application_type',
            field=models.CharField(default='analytics', max_length=100),
        ),
        migrations.AddField(
            model_name='database',
            name='budget',
            field=models.CharField(default='high', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='compliance_needs',
            field=models.CharField(default='high', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='database',
            name='description',
            field=models.TextField(default='Fully managed data warehouse for enterprise workloads.'),
        ),
        migrations.AddField(
            model_name='database',
            name='geographic_distribution',
            field=models.CharField(default='multi', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='query_complexity',
            field=models.CharField(default='complex', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='read_write_operations',
            field=models.CharField(default='heavy_reads', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='scale',
            field=models.CharField(default='enterprise', max_length=50),
        ),
        migrations.AddField(
            model_name='database',
            name='traffic',
            field=models.CharField(default='high', max_length=50),
        ),
        migrations.AlterField(
            model_name='database',
            name='advantages',
            field=models.TextField(default='High performance for analytics, integrates well with AWS ecosystem, automated backups.'),
        ),
        migrations.AlterField(
            model_name='database',
            name='benefits',
            field=models.TextField(default='Columnar storage for fast queries, massively parallel processing, easy scaling.'),
        ),
        migrations.AlterField(
            model_name='database',
            name='best_use_cases',
            field=models.TextField(default='Data warehousing, business intelligence, large-scale analytics.'),
        ),
        migrations.AlterField(
            model_name='database',
            name='companies_using',
            field=models.TextField(default='Yelp, McDonalds, Lyft, Comcast.'),
        ),
        migrations.AlterField(
            model_name='database',
            name='cost',
            field=models.TextField(default='Pay for the cluster size and usage, options for reserved instances to save costs.'),
        ),
        migrations.AlterField(
            model_name='database',
            name='cost_analysis',
            field=models.CharField(default='Pricing depends on cluster size and usage; reserved instances offer cost savings.', max_length=100),
        ),
        migrations.AlterField(
            model_name='database',
            name='data_operations',
            field=models.TextField(default='Read-heavy analytical workloads, complex queries across large datasets.'),
        ),
        migrations.AlterField(
            model_name='database',
            name='disadvantages',
            field=models.TextField(default='Performance optimization requires expertise, can be expensive for large clusters.'),
        ),
        migrations.AlterField(
            model_name='database',
            name='existing_teams_to_connect',
            field=models.TextField(default='BI Teams, Data Engineering, Performance Optimization teams.'),
        ),
        migrations.AlterField(
            model_name='database',
            name='name',
            field=models.CharField(default='Amazon Redshift', max_length=100),
        ),
    ]
